# Generated by Django 4.2.3 on 2023-08-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.URLField()),
                ('author', models.CharField()),
                ('time_to_cook', models.IntegerField()),
                ('ingredients', models.TextField(max_length=1000)),
                ('nutrition', models.TextField(max_length=1000)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('how_to_cook', models.TextField()),
                ('number_of_portions', models.IntegerField()),
                ('date_of_publication', models.DateField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
